### ISSUE TITLE
dvisvgm BinaryBuilder

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/MakieTeX.jl#5]
https://dvisvgm.de/Downloads/
Deps:
- [x] Clipper
- [ ] FontForge
- [x] FreeType
- [x] Ghostscript
- [ ] kpathsea
- [x] OpenSSL 
- [ ] potrace
- [ ] ttfautohint
- [ ] woff2 brotli
- [x] xxHash
- [x] zlib

**Comment by asinghvi17** [comment]
Turns out that dvisvgm is suboptimal - conversion using pdftocairo (Poppler_jll), Ghostscript (Ghostscript_jll) and a Perl script (Perl_jll) for PDF cropping seem to yield a superior output.  I've switched to that pipeline for this.


The only other thing we would need for this to work would be a LaTeX JLL, but I don't think that's going to happen anytime soon :D
